### ISSUE TITLE
[CHECKLIST] Relayer integration testing w/ gadget

### ISSUE THREAD

**Issue by drewstone** [tangle-network/blueprint#36]
# Overview
The relayer will play the same role it always does and we should integrate it into the gadget for proper E2E tests. In order to get back to feature parity with our bridge system, we will want the relayer to likely run in parallel to a gadget or present some new avenues and ways of configuring (possibly a docker-compose'd setup).

## Lifecycle for Hubble Bridge feature parity
1. User makes a deposit on the bridge.
2. **Relayers** see the deposit.
3. **Relayers** vote on the `SigningRules` contract instead of `dkg-proposals` pallet.
4. Successful voting of `SigningRules` proposal triggers a job submission
5. **Gadgets** see the job and begin executing
6. **Gadgets** submit the completed job onchain
7. **Relayers** see the completed job and relay the data back to `SignatureBridge`.

# Checklist
- [ ] Integrate the relayers into either docker-compose or parallel process to be run alongside/within gadget.
- [ ] Implement new handlers to support `SigningRules` contract voting (currently we support `dkg-proposals`)
- [ ] Implement new event watchers for `pallet-jobs` on Tangle (currently we support `dkg-proposal-handler`)
- [ ] Implement tests

### Discussion
1. The relayer repo has a tremendous amount of crates. These crates have not proven themselves to be useful / generalizable in other repos. I think we should consider how to make some of these crates useful for simple tasks INDEPENDENT of their usefulness to the relayer. Things like logging, event listening, transaction submitting etc. should be lighter-weight so they can be used in more contexts. For example, we should've been able to reuse that transaction queuing system for the `faucet` but alas its not build that way. We're building tools that are not reusable enough and cause us to rewrite things in different places IMO.
2. I think the new handlers/event watchers should go INSIDE gadget repo if we are integrating directly there. The vision I had for the relayer is that these crates could be drop-in dependencies for building event listening/transacting systems outside of the main relayer repo. If we just keep layering more event watchers in `relayer` I have a feeling this is bloat and not the best route.
3. In order to test the relayer <-> gadget combo I'm thinking of whether it makes sense to have in our framework a **server** based middleware that can be a drop-in replacement for the blockchain connection. This way we can use a test EVM to deposit/vote on our contracts and use a server to coordinate job submission/delegation. It would be effectively a way to run gadgets without a blockchain for job management in the attempt to test purely this logic. This might be unnecessary but pushing the discussion anyway.
