### ISSUE TITLE
[TASK] Add smoldot integration to use gadget as a light-client

### ISSUE THREAD

**Issue by drewstone** [tangle-network/blueprint#46]
# Overview
Being able to run the gadget separate from a validator node will be beneficial for validators who want to keep their MPC workers organized and separate. This would also allow a single validator to scale their operation beyond the constraints of a single node (a validator could run multiple gadgets that each run one of the roles).

Doing so requires having a hook against the finality mechanism. Smoldot could provide the finality capabilities needed here, while also being beneficial to the network at large (by creating more node diversity).

### Tasks
- [ ] Research and explore smoldot integration
- [ ] Run the gadget against the finality notification handler used by smoldot
- [ ] Test using a validator + gadget separate setup

### Considerations
By separating these operations we may want to add a _**proxy**_-like system for MPC workers where validators can use their `role` key to set a proxy for MPC job submissions. This account would then be stored and managed by the gadget and separate operations, dealing with key management entirely separately. The `role` key wouldn't need to leave the validator in this case. The `role` or `stash` key would be in charge of setting up these proxies for different roles, maybe even going as fine grained as having a different proxy for different services. Simple is best here nonetheless.

**Comment by tbraun96** [comment]
For reference: https://docs.rs/crate/smoldot-light/0.14.0/source/examples/basic.rs
